### ISSUE TITLE
Tambahin gambar/image pada saat client ketik menu

### ISSUE THREAD

**Issue by KiroFyzu** [botstylee/botstylee#110]
semoga dijawab dan dibuatin

**Comment by findme-19** [comment]
> semoga dijawab dan dibuatin

https://github.com/botstylee/botstylee/blob/35c0495ec885ef2fd8f910d7d85fac09345c22e5/plugins/menu.cjs#L358

Hapus aja line ini yang bagian 
``` js 
{
asLocation : true
}

**Comment by botstylee** [comment]
> > semoga dijawab dan dibuatin
> 
> https://github.com/botstylee/botstylee/blob/35c0495ec885ef2fd8f910d7d85fac09345c22e5/plugins/menu.cjs#L358
> 
> Hapus aja line ini yang bagian
> 
> ```js
> {
> asLocation : true
> } 
> ```

Nomer wamu yg aktif mana bruh, kok saya chat gak aktif
