### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by prioprasty** [botstylee/botstylee#132]
![Screenshot_2022-08-20-22-41-01-669_com termux](https://user-images.githubusercontent.com/74877643/185755086-364cc082-d891-40da-a9d8-cc4fcf89a7b1.jpg)

Cara atasi nya gimana ya bang?

**Comment by botstylee** [comment]
> ![Screenshot_2022-08-20-22-41-01-669_com termux](https://user-images.githubusercontent.com/74877643/185755086-364cc082-d891-40da-a9d8-cc4fcf89a7b1.jpg)
> 
> Cara atasi nya gimana ya bang?

Npm i yarn udah kah ?

**Comment by findme-19** [comment]
> ![Screenshot_2022-08-20-22-41-01-669_com termux](https://user-images.githubusercontent.com/74877643/185755086-364cc082-d891-40da-a9d8-cc4fcf89a7b1.jpg)
> 
> Cara atasi nya gimana ya bang?

```bash
npm install -g npm@6.14.14
```
