### ISSUE TITLE
Error ngab

### ISSUE THREAD

**Issue by Bridger-12** [botstylee/botstylee#136]
fitur sticker nya error banh, page not found
https://api.xteam.xyz/sticker/wm

![Firefox_Screenshot_2022-09-15T21-58-44 993Z](https://user-images.githubusercontent.com/111205994/190522435-bcc3a76b-93cd-429d-8caf-92be898f823a.png)

**Comment by botstylee** [comment]
> fitur sticker nya error banh, page not found https://api.xteam.xyz/sticker/wm
> 
> ![Firefox_Screenshot_2022-09-15T21-58-44 993Z](https://user-images.githubusercontent.com/111205994/190522435-bcc3a76b-93cd-429d-8caf-92be898f823a.png)

Bentar bentar stiker wm di xteam bukannya gak ada ya, lagi pula kalo mau bisa kayak toimg, stiker, wm kudu install modul ffmpeg, imagemagick sama libwebp

**Comment by findme-19** [comment]
> > fitur sticker nya error banh, page not found https://api.xteam.xyz/sticker/wm
> > ![Firefox_Screenshot_2022-09-15T21-58-44 993Z](https://user-images.githubusercontent.com/111205994/190522435-bcc3a76b-93cd-429d-8caf-92be898f823a.png)
> 
> Bentar bentar stiker wm di xteam bukannya gak ada ya, lagi pula kalo mau bisa kayak toimg, stiker, wm kudu install modul ffmpeg, imagemagick sama libwebp

Sticker nggk ada masalah
