### ISSUE TITLE
bot sering mati sendiri

### ISSUE THREAD

**Issue by ofcgabrielhrz** [botstylee/botstylee#137]
bang kenapa bot sering mati sendiri yak ?

**Comment by findme-19** [comment]
Baca lognya

**Comment by ofcgabrielhrz** [comment]
![Uploading Screenshot_2022-10-03-06-35-51-picsay.png…]()

**Comment by ofcgabrielhrz** [comment]
![Screenshot_2022-10-03-06-35-51-picsay](https://user-images.githubusercontent.com/104119101/193481684-905e4213-b4c6-49cf-b0f5-fa970bcbe085.png)
malah gini bang

**Comment by findme-19** [comment]
> ![Screenshot_2022-10-03-06-35-51-picsay](https://user-images.githubusercontent.com/104119101/193481684-905e4213-b4c6-49cf-b0f5-fa970bcbe085.png) malah gini bang

Sinyalnya itu bang

**Comment by ofcgabrielhrz** [comment]
oalah jelek banget nih vps wkkw

**Comment by ofcgabrielhrz** [comment]
thanks you
