### ISSUE TITLE
Fix menu

### ISSUE THREAD

**Issue by Natx-C** [botstylee/botstylee#24]

**Comment by aowjqoidjidw** [comment]
> Menu kenapa emangnya

ga muncul

**Comment by Natx-C** [comment]
> Menu kenapa emangnya

Gamuncul menunya

**Comment by botstylee** [comment]
Coba silahkan di coba sudah di fix sama ghost

**Comment by Ghost19-ui** [comment]
> > Menu kenapa emangnya
> 
> ga muncul

Sudah saya fix bang

**Comment by Natx-C** [comment]
> Coba silahkan di coba sudah di fix sama ghost

Oke makasih dah bisa min
