### ISSUE TITLE
Bug Bot Stylee (Please Fix it!)

### ISSUE THREAD

**Issue by Sly-Zipy** [botstylee/botstylee#3]
Permisi bang mau nyampein beberapa bug di botstylee
1. Command Owner banyak bug  seperti
- #oadd
- #opromote
- #odemote
- #okick
dan sebagainya

2. User Premium nya ga working
ketika sudah di promote member ke premium user tapi mereka tetep ga bisa meng access command/fitur dari premium user tersebut
contoh command yang ga bisa di pake kalo udah di tambahin ke premium user
- #gajian/#gaji

3. Botstylee juga ga bisa mengacess command/fitur Admin
untuk bug/error pada admin feature itu ga bisa melakukan kick, mute, promote, demote walaupun botstylee telah menjadi admin group.

4. untuk antiLink, antiBadword, antiVirtex, enable/disable nya ga working (tolong di fix!)

5. sebagian command tidak berfungsi

untuk Developer BotStylee jika ada waktu diharapkan untuk bisa memperbaiki nya terimakasih

- user BotStylee

**Comment by botstylee** [comment]
Bug akan di perbaiki setelah ujian kampus selesai ya seminggu lagi soal bentar lagi saya upm pemrograman

**Comment by botstylee** [comment]
> Permisi bang mau nyampein beberapa bug di botstylee
> 
> 1. Command Owner banyak bug  seperti
> 
> * #oadd
> * #opromote
> * #odemote
> * #okick
>   dan sebagainya
> 
> 1. User Premium nya ga working
>    ketika sudah di promote member ke premium user tapi mereka tetep ga bisa meng access command/fitur dari premium user tersebut
>    contoh command yang ga bisa di pake kalo udah di tambahin ke premium user
> 
> * #gajian/#gaji
> 
> 1. Botstylee juga ga bisa mengacess command/fitur Admin
>    untuk bug/error pada admin feature itu ga bisa melakukan kick, mute, promote, demote walaupun botstylee telah menjadi admin group.
> 2. untuk antiLink, antiBadword, antiVirtex, enable/disable nya ga working (tolong di fix!)
> 3. sebagian command tidak berfungsi
> 
> untuk Developer BotStylee jika ada waktu diharapkan untuk bisa memperbaiki nya terimakasih
> 
> * user BotStylee

Untuk anti semuanya pake #on ya bukan #enable lagi karena biar simpel

**Comment by rizkiramadhan4617** [comment]
> Permisi bang mau nyampein beberapa bug di botstylee
> 
> 1. Command Owner banyak bug  seperti
> 
> * #oadd
> * #opromote
> * #odemote
> * #okick
>   dan sebagainya
> 
> 1. User Premium nya ga working
>    ketika sudah di promote member ke premium user tapi mereka tetep ga bisa meng access command/fitur dari premium user tersebut
>    contoh command yang ga bisa di pake kalo udah di tambahin ke premium user
> 
> * #gajian/#gaji
> 
> 1. Botstylee juga ga bisa mengacess command/fitur Admin
>    untuk bug/error pada admin feature itu ga bisa melakukan kick, mute, promote, demote walaupun botstylee telah menjadi admin group.
> 2. untuk antiLink, antiBadword, antiVirtex, enable/disable nya ga working (tolong di fix!)
> 3. sebagian command tidak berfungsi
> 
> untuk Developer BotStylee jika ada waktu diharapkan untuk bisa memperbaiki nya terimakasih
> 
> * user BotStylee

Hai yang terhormat Sly -zipy ,Maaf atas ketidak nyaman nan nya,Kami akan memperbarui fitur nya,Tetap stay mengunakan botstyle 👍
