### ISSUE TITLE
Antilink

### ISSUE THREAD

**Issue by Natx-C** [botstylee/botstylee#57]
Antilink nda work biar work apakah make node . --restrict ?

**Comment by botstylee** [comment]
> Antilink nda work biar work apakah make node . --restrict ?

![Screenshot_2021-11-20-09-59-58-44_2768c6f3dd71c987876b7b9730ce2453](https://user-images.githubusercontent.com/85060672/142712069-2c27fc8e-0511-44c8-8fa2-7ceef8b72668.png)
Ini work kok aman aman aja
