### ISSUE TITLE
Error scan qr

### ISSUE THREAD

**Issue by peraaxd** [botstylee/botstylee#89]
![Screenshot_20220415-130951](https://user-images.githubusercontent.com/71998161/163528997-c7a2987e-f282-4eed-932f-85da9564cc44.png)

Ini kenapa ya bang kok gk bisa scan qr😥.. apa gara gara wa web nya barusan update🤔

**Comment by botstylee** [comment]
> ![Screenshot_20220415-130951](https://user-images.githubusercontent.com/71998161/163528997-c7a2987e-f282-4eed-932f-85da9564cc44.png)
> 
> Ini kenapa ya bang kok gk bisa scan qr😥.. apa gara gara wa web nya barusan update🤔

Mungkin saja sudah ke multi perangkat alias multi device

**Comment by peraaxd** [comment]
> > ![Screenshot_20220415-130951](https://user-images.githubusercontent.com/71998161/163528997-c7a2987e-f282-4eed-932f-85da9564cc44.png)
> > Ini kenapa ya bang kok gk bisa scan qr😥.. apa gara gara wa web nya barusan update🤔
> 
> Mungkin saja sudah ke multi perangkat alias multi device

Okelah
