### ISSUE TITLE
req:

### ISSUE THREAD

**Issue by natxdixie** [botstylee/botstylee#91]
add download bang, kya play,tiktok,fb,ig

**Comment by botstylee** [comment]
> add download bang, kya play,tiktok,fb,ig

Masih tahap pengerjaan Fiture itu

**Comment by BrunoSobrino** [comment]
@botstylee Hai, nama saya Bruno Sobrino dan saya dari Meksiko, jika membantu, saya berhasil membuat perintah ini berdasarkan kode dari bochilteam/games-wabot-md, ini berfungsi dengan #play dan #play2

File teks terlampir dengan kode karena saya tidak tahu cara membuat kontribusi :)

Ini bekerja sedikit lambat tetapi memenuhi fungsi video dan audio

[play.txt](https://github.com/botstylee/botstylee/files/8914137/play.txt)

**Comment by botstylee** [comment]
> @botstylee Hai, nama saya Bruno Sobrino dan saya dari Meksiko, jika membantu, saya berhasil membuat perintah ini berdasarkan kode dari bochilteam/games-wabot-md, ini berfungsi dengan #play dan #play2
> 
> File teks terlampir dengan kode karena saya tidak tahu cara membuat kontribusi :)
> 
> Ini bekerja sedikit lambat tetapi memenuhi fungsi video dan audio
> 
> [play.txt](https://github.com/botstylee/botstylee/files/8914137/play.txt)

Thank you for wanting to be a contributor

**Comment by findme-19** [comment]
> add download bang, kya play,tiktok,fb,ig

Sudah ada bang
